# Generated by Django 6.1.1 on 2026-09-05 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=1000, unique=True)),
                ('platform', models.CharField(choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('total_reviews_count', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_status', models.CharField(blank=True, default='', max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_score', models.FloatField(default=0.0)),
                ('fake_review_percentage', models.FloatField(default=0.0)),
                ('velocity_spike_detected', models.BooleanField(default=False)),
                ('dark_patterns_detected', models.JSONField(blank=True, default=list)),
                ('aspects_sentiment', models.JSONField(blank=True, default=dict)),
                ('summary_reasons', models.JSONField(blank=True, default=list)),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_report', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, default='Anonymous', max_length=255)),
                ('rating', models.FloatField()),
                ('review_title', models.CharField(blank=True, default='', max_length=500)),
                ('review_text', models.TextField()),
                ('review_date', models.DateField(blank=True, null=True)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('is_flagged_fake', models.BooleanField(default=False)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
        ),
    ]
