# Generated by Django 6.1.1 on 2026-09-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business_category',
            field=models.CharField(choices=[('ecommerce', 'E-Commerce Product'), ('restaurant', 'Restaurant / Cafe'), ('healthcare', 'Hospital / Medical Clinic'), ('automotive', 'Automobile Showroom / Service Center'), ('general_business', 'General Local Business')], default='ecommerce', max_length=30),
        ),
        migrations.AddField(
            model_name='review',
            name='is_local_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_total_reviews',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='platform',
            field=models.CharField(choices=[('amazon', 'Amazon'), ('flipkart', 'Flipkart'), ('google_maps', 'Google Maps')], max_length=20),
        ),
    ]
